
// This file is automatically generated. Do not modify it manually.

import type { FirebaseOptions } from 'firebase/app';

function parseFirebaseConfig(): FirebaseOptions {
    const configString = process.env.NEXT_PUBLIC_FIREBASE_CONFIG;
    if (!configString) {
        console.error("Firebase config environment variable NEXT_PUBLIC_FIREBASE_CONFIG is not set.");
        return {};
    }
    try {
        // Attempt to parse directly first
        return JSON.parse(configString);
    } catch (e) {
        console.warn("Could not parse NEXT_PUBLIC_FIREBASE_CONFIG directly, attempting to manually extract keys. This can happen in some environments like Vercel.", e);
        
        // If direct parsing fails, manually extract the keys.
        // This is more robust against environments that might strip quotes.
        const extractValue = (key: string) => {
            const regex = new RegExp(`"${key}"\\s*:\\s*"([^"]+)"`);
            const match = configString.match(regex);
            return match ? match[1] : undefined;
        };

        const config: FirebaseOptions = {
            apiKey: extractValue("apiKey"),
            authDomain: extractValue("authDomain"),
            projectId: extractValue("projectId"),
            storageBucket: extractValue("storageBucket"),
            messagingSenderId: extractValue("messagingSenderId"),
            appId: extractValue("appId"),
            measurementId: extractValue("measurementId"),
        };
        
        if (!config.apiKey || !config.projectId) {
            console.error("Failed to manually parse NEXT_PUBLIC_FIREBASE_CONFIG. Critical keys (apiKey, projectId) are missing. Received:", configString);
            return {};
        }
        
        return config;
    }
}

export const firebaseConfig: FirebaseOptions = parseFirebaseConfig();
