// This file is automatically generated. Do not modify it manually.

import type { FirebaseOptions } from 'firebase/app';

function parseFirebaseConfig(): FirebaseOptions {
    const configString = process.env.NEXT_PUBLIC_FIREBASE_CONFIG;
    if (!configString) {
        console.error("Firebase config environment variable NEXT_PUBLIC_FIREBASE_CONFIG is not set.");
        // Return a dummy config to avoid crashing the build,
        // but Firebase will fail to initialize.
        return {};
    }
    try {
        return JSON.parse(configString);
    } catch (e) {
        console.error("Failed to parse NEXT_PUBLIC_FIREBASE_CONFIG. Make sure it's a valid JSON string.", e);
        return {};
    }
}

export const firebaseConfig: FirebaseOptions = parseFirebaseConfig();
